on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run the action on'
        required: true
        default: 'amondnet/claude-code-action'
      force:
        description: 'Force refresh the token even if it is still valid'
        required: false
        default: false
        type: boolean

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    name: Refresh Claude Token for Repository
    steps:
      - uses: actions/checkout@v4
      - id: refresh-token
        uses: ./
        with:
          mode: repo
          target: ${{ github.event.inputs.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          force: '${{ github.event.inputs.force }}'

